# Generated by Django 5.0.6 on 2024-06-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0019_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='beat',
        ),
        migrations.AddField(
            model_name='playlist',
            name='beats',
            field=models.ManyToManyField(blank=True, to='beats.beats'),
        ),
    ]
